#!/bin/zsh

# User variables
logged_in_user=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }')
uid=$(id -u "$logged_in_user")

# Kill Cricut process if running
if pgrep "CricutTaskbarApplication"; then
    killall "CricutTaskbarApplication"
fi

# Run installer
/private/tmp/CricutDesignSpace.app/Contents/MacOS/osx-x86_64 --mode unattended

# Open Cricut Design Space as user
launchctl asuser $uid open "/Users/${logged_in_user}/Library/Application Support/Cricut Design Space/Web/taskbar-application-osx/Release/CricutTaskbarApplication.app"

# Clean up
rm -rf /private/tmp/CricutDesignSpace.app